# Generated by Django 3.2.16 on 2023-02-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_employee_gender'),
    ]

    operations = [
    ]
