# Generated by Django 3.2.16 on 2023-02-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230215_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbook',
            name='bill',
            field=models.IntegerField(default=0),
        ),
    ]
