# Generated by Django 3.2.16 on 2023-02-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_clientbook_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='received',
            field=models.DateTimeField(),
        ),
    ]
