# Generated by Django 3.2.16 on 2023-02-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_generalledger_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='received',
            field=models.IntegerField(),
        ),
    ]
