# Generated by Django 3.2.16 on 2023-02-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_generalledger_received'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='clientbook',
            name='client_id',
        ),
        migrations.DeleteModel(
            name='GeneralLedger',
        ),
        migrations.RemoveField(
            model_name='salarybook',
            name='emp_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientBook',
        ),
        migrations.DeleteModel(
            name='DateAttendance',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='SalaryBook',
        ),
    ]
