# Generated by Django 3.2.16 on 2023-02-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_attendance_client_clientbook_dateattendance_employee_generalledger_salarybook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientbook',
            name='bill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clientbook',
            name='payment',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='received',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='spending',
            field=models.IntegerField(null=True),
        ),
    ]
