# Generated by Django 3.2.16 on 2023-02-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_generalledger_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
