# Generated by Django 3.2.16 on 2023-02-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20230224_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalledger',
            options={'ordering': ['id']},
        ),
    ]
