# Generated by Django 3.2.16 on 2023-02-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_generalledger_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientbook',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='salarybook',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
