# Generated by Django 3.2.16 on 2023-03-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20230313_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientbook',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='clientbook',
            old_name='bill',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='salarybook',
            old_name='emp_id',
            new_name='employee',
        ),
        migrations.AddField(
            model_name='clientbook',
            name='unit_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='date',
            field=models.DateField(),
        ),
    ]
