# Generated by Django 3.2.16 on 2023-03-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20230317_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarybook',
            name='date',
            field=models.DateField(),
        ),
    ]
