# Generated by Django 3.2.16 on 2023-03-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_salarybook_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbook',
            name='unit_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
