# Generated by Django 3.2.16 on 2023-04-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_clientbook_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbook',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
